#!/usr/bin/env python
"""
 Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.

 Permission is hereby granted, free of charge, to any person obtaining a copy of this
 software and associated documentation files (the "Software"), to deal in the Software
 without restriction, including without limitation the rights to use, copy, modify,
 merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 permit persons to whom the Software is furnished to do so.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""


import json

import rospy
import actionlib
from tts.msg import SpeechAction, SpeechGoal
from std_msgs.msg import String

class Rekognizer:

    def __init__(self, rekognition_topic="/rekognition/results"):

        #Listen for rekognition results
        self.rekognition_subscriber = rospy.Subscriber(rekognition_topic, String, self.rekognize_callback)

        #Action client for Polly
        self.client = actionlib.SimpleActionClient("tts", SpeechAction)

    def rekognize_callback(self, msg):
        image_ids = []
        try:
            msg = json.loads(msg.data)
            if msg["FaceSearchResponse"]:
                rospy.logdebug("Rekognition result has FaceSeachResponse, looking for matched faces")
                for face in msg['FaceSearchResponse'][0]['MatchedFaces']:
                    rospy.logdebug("Matched face: %s", face)
                    # Default 'unnamed' is required for indexed images without ExternalImageId
                    name = face['Face'].get('ExternalImageId', 'unknown')
                    rospy.logdebug("Matched face has name: %s", name)
                    image_ids.append(name)
            else:
                return
        except ValueError as e:
            rospy.logerr("Error loading json message from rekognition:\n%s", e)
            return

        if not image_ids:
            rospy.loginfo("Rekognition result has no faces")
            return 

        names =" and ".join([image_id.replace("_"," ") for image_id in image_ids])

        #Create Polly Request
        self.client.wait_for_server()

        goal = SpeechGoal()
        goal.text = "I see {}".format(names)
        rospy.loginfo("Sending Polly request: '%s'", goal.text)
        self.client.send_goal(goal)



def main():
    rospy.init_node("rekognize", log_level=rospy.INFO)
    
    rekognizer = Rekognizer()
    
    rospy.spin()


if __name__ == '__main__':
    main()

